services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: app_mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sile_i_dlugie_haslo_do_bazy_8263_danych!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Sile_i_dlugie_haslo_do_bazy_8263_danych!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_api
    depends_on:
      db:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: "Server=db,1433;Database=app_db;User Id=sa;Password=Sile_i_dlugie_haslo_do_bazy_8263_danych!;TrustServerCertificate=True"
      APPLY_MIGRATIONS: "true"
    ports:
      - "8080:8080"

volumes:
  mssql_data:
