// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_src;

#nullable disable

namespace backend_src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004233938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend_src.Raport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyMezczyzna")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyUwzglednialOkresChoroby")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmeryturaRzeczywista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmeryturaUrealniona")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KodPocztowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OczekiwanaEmerytura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SrodkiNaKoncie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SrodkiNaSubkoncie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wiek")
                        .HasColumnType("int");

                    b.Property<decimal>("Wynagrodzenie")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Raports");
                });
#pragma warning restore 612, 618
        }
    }
}
